set_property PACKAGE_PIN Y9 [ get_ports clk ]
set_property IOSTANDARD LVCMOS33 [ get_ports clk ]
create_clock - period 10.000 - name sys_clk - waveform {0 5} [ get_ports clk ]
set_property PACKAGE_PIN T18 [ get_ports rst ]
set_property IOSTANDARD LVCMOS33 [ get_ports rst ]
set_property PACKAGE_PIN R18 [ get_ports btn_in ]
set_property IOSTANDARD LVCMOS33 [ get_ports btn_in ]
set_property PACKAGE_PIN R16 [ get_ports gap ]
set_property IOSTANDARD LVCMOS33 [ get_ports gap ]
set_property PACKAGE_PIN P16 [ get_ports word_gap ]
set_property IOSTANDARD LVCMOS33 [ get_ports word_gap ]
set_property PACKAGE_PIN V22 [ get_ports led_clk ]
set_property IOSTANDARD LVCMOS33 [ get_ports led_clk ]
